appName: paymentservice
appImage: gcr.io/google-samples/microservices-demo/paymentservice
appVersion: v0.5.0
appReplicas: 2
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"

serviceType: ClusterIP
servicePort: 50051
